service: cake-ordering-system-nodejs
frameworkVersion: "2"

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221

functions:
  createOrder:
    handler: handler.createOrder
    events:
      - httpApi: "POST /order"
